gps:
  baudrate: 921600
  odometer: 0
  port: '/dev/ttyACM0'  # port: '/dev/ttyUSB0'
ecu: 
  tank_size: 17 # gal
  oil_low_limit: 15 # psi
  voltage_low_limit: 11.5 #volts
  engine_temp_high: 240 # F degrees
 